version: '3.1'
services:

  db:
    container_name: mariadb11.4.5-ubi9
    image: mariadb:11.4.5-ubi9
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: example
    ports:
      - 3308:3306

  adminer:
    container_name: adminer5.1.0-standalone
    image: adminer:5.1.0-standalone
    restart: always
    ports:
      - 9080:8080

  smtp4dev:
    image: rnwood/smtp4dev:v3
    restart: always
    ports:
      - 9081:80
      - 9025:25
      - '143:143'
